import styled from "@emotion/styled";
import { User } from "../models/User";


type Props = {
    content: string;
    timestamp: Date;
    sender: User; 
    isAutoGenerated: boolean; 

    onClick?: () => void;
}


const MessageItem = ({ content, timestamp, onClick, sender}: Props) => {
    return (
        <Container onClick={onClick}>
        <Avatar src={sender.avatar} />
        <MessageContent>
          <div>
            <strong>{sender.name}</strong>
          </div>
          <div>{content}</div>
        </MessageContent>
        <Timestamp>{timestamp.toDateString()}</Timestamp>
      </Container>

    )
}

const Container = styled.div`
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.5rem;
  cursor: ${({ onClick }) => (onClick ? 'pointer' : 'initial')};
  border-radius: 0.25rem;
  transition: background-color 0.1s ease-in-out;

  &:hover {
    background-color: #23272a;
  }
`;

const Avatar = styled.img`
  height: 2rem;
  width: 2rem;
  border-radius: 2rem;
`;

const MessageContent = styled.div`
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
`;

const Timestamp = styled.div`
  color: #999;
  font-size: 0.8rem;
`;

export default MessageItem;