import MessageItem from "./MessageItem"
import {User} from "../models/User";
import { useMessage } from "../hooks/useMessage";
import { Message } from "../models/Message";


type Props = {
    profile: User;
    other: User;
    newMessages: Message[];
  };

const MessageList = ({ profile, other, newMessages}: Props ) => {

    const{message, loading : messageLoading}= useMessage(profile, other);

  const totalMessage= newMessages.length> 0 ?  [...message, ...newMessages]: message;

    return(

        <div>
        {messageLoading ? (
          <div>Loading messages...</div>
        ) : (

          totalMessage.map(({ content, timestamp, sender, id , isAutoGenerated}) => (
            <MessageItem
              key={id}
              content={content}
              timestamp={timestamp}
              sender={sender}
              isAutoGenerated= {isAutoGenerated} 
            />
            
          ))
        )}
      </div>
      
)
};

export default MessageList