
import UserList from "./components/UserList";
import styled from "@emotion/styled";
import UserItem from "./components/UserItem";
import { useUsers } from "./hooks/useUsers";
import { useProfile } from "./hooks/useProfil";
import MessageList from "./components/MessageList";
import { useState} from "react";
import {User} from "./models/User";
import MessageHeader from "./components/messageHeader";
import SearchBar from "./components/SearchBar";
import EditMessage from "./components/EditMessage";
import { Message } from "./models/Message";



const App = () => {

const{users, loading : UsersLoading}= useUsers();
const{profile, loading : profileLoading}= useProfile();
const[other, setOther ]= useState<User>();
const [messages, setMessages] = useState<Message[]>([]);
const [manuallyEnteredMessages, setManuallyEnteredMessages] = useState<Message[]>([]);

const handleSendMessage = (newMessages: Message[]) => {
  const autoGenerated = newMessages.filter((message) => message.isAutoGenerated);

  // add messages automatiques 
  if (autoGenerated.length > 0) {
    setMessages([...messages, ...autoGenerated]);
  }

  const manuallyEntered = newMessages.filter((message) => !message.isAutoGenerated);

  // add messages saisis manuellement 
  if (manuallyEntered.length > 0) {
    setManuallyEnteredMessages([...manuallyEnteredMessages, ...manuallyEntered]);
  }


};

if(profileLoading || UsersLoading || !profile)
{
  return<div>loading</div>
}

  return (
    <AppContainer>
      <LeftContainer>
        <UserListContainer>
          <UserList users= {users} onClick = {setOther} />
        </UserListContainer>
        <ProfileContainer>
          <UserItem avatar={profile?.avatar} name={profile.name}  />
        </ProfileContainer>
      </LeftContainer>

      <ChatContainer>
        <HeaderChatContainer>
          <MessageHeader avatar={profile?.avatar} name={profile.name}/>
          <SearchBar />
        </HeaderChatContainer>
        <BodyMessage>
          {other && <MessageList profile={profile}  other={other} newMessages={manuallyEnteredMessages}/>

          }
        </BodyMessage>
        <EditMessageContainer>
        <EditMessage onSendMessage={handleSendMessage} profile={profile} messages={messages}  />
        </EditMessageContainer>
      </ChatContainer>
    
    </AppContainer>
  )
}

const AppContainer = styled.div`
  display: flex;
  width: 100%;
`
const LeftContainer = styled.div`
  display: flex;
  flex-direction: column;
  width: 16rem;
  height: 100vh;
  position: relative;

`
const UserListContainer = styled.div`
border-right: 1px solid #bdbdbd;
overflow-y : scroll;
flex:1;

`
const ChatContainer = styled.div`
 flex: 1;
 display: flex;
 flex-direction: column;
 width: 16rem;
 height: 100vh;
 position: relative;
`

const ProfileContainer = styled.div`
background-color: #343434;
box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22);
max-height: 8%
`

const HeaderChatContainer = styled.div`
  background-color: #36393f;
  color: white;
  padding: 16px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  border-bottom: 1px solid #202225;
  font-weight: bold;
`;

const BodyMessage = styled.div`
  background-color: #2f3136;
  flex: 1;
  overflow-y: scroll;
  padding: 16px;
  scrollbar-width: thin;
  scrollbar-color: #202225 #2f3136;

  &::-webkit-scrollbar {
    width: 6px;
  }

  &::-webkit-scrollbar-thumb {
    background-color: #2f3136;
    border: 2px solid #202225;
  }
`;

const EditMessageContainer = styled.div`
  background-color: #40444b;
  padding: 16px;
  border-top: 1px solid #202225;
`;
export default App
