import { User } from "../models/User";
import {faker} from '@faker-js/faker';

//pour simuler un temps de chargement
const delay = (time: number) => {
    return new Promise(resolve => setTimeout(resolve, time));
}

//creation de user a partir de Faker
export const createUser = (id:number) => ({
    id,
    name: faker.person.fullName(),
    avatar: faker.image.avatar(),
})


export const getUsers = async () => {

    const array = Array.from(Array(50).keys())
    await delay(100)
    return array.map(createUser)
}

//crée des mess 
//id en tostring car uuid pour les mess manuels
export const getMessage = async (other: User, profile: User) => {

    const array = Array.from(Array(8).keys())
    await delay(500)
    return  {
        other,
        profile,
        messages: array.map((id) => ({
            id: id.toString(),
            content: faker.hacker.phrase(),
            sender: id % 2===0 ? other: profile,
            timestamp: new Date(),
            isAutoGenerated: true, 
        }) ),
        
    };
}